let title = "Lesson 2";
let screens = "Простые, Сложные, Интерактивные";
let screenPrice = 45;
let rollback = 72;
let fullPrice = 200000;
let adaptive = true;

console.log(typeof(title));
console.log(typeof(fullPrice));
console.log(typeof(adaptive));
console.log(" ");
console.log(screens.length);
console.log(" ");
console.log(`Стоимость верстки экранов ${screenPrice} рублей/ долларов/гривен/юани`);
console.log(`Стоимость верстки экранов ${fullPrice} рублей/ долларов/гривен/юани`);
console.log(" ");
console.log(screens.toLowerCase().split(","));
console.log(" ");
rollback = fullPrice * (rollback/100);
console.log(`Процент отката посреднику за работу: ${rollback}`);